# Generated by Django 6.0.4 on 2026-04-25 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(verbose_name='Minuto')),
                ('x_start', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='X Inicio')),
                ('y_start', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Y Inicio')),
                ('x_end', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='X Fin')),
                ('y_end', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Y Fin')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Distancia (m)')),
                ('is_key_pass', models.BooleanField(default=False, verbose_name='Pase Clave')),
                ('is_cross', models.BooleanField(default=False, verbose_name='Centrada')),
                ('is_through_ball', models.BooleanField(default=False, verbose_name='Pase Filtrado')),
                ('successful', models.BooleanField(verbose_name='Exitoso')),
                ('assist', models.BooleanField(default=False, verbose_name='Asistencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_made', to='players.player', verbose_name='De')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='matches.match', verbose_name='Partido')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='teams.team', verbose_name='Equipo')),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_received', to='players.player', verbose_name='A')),
            ],
            options={
                'verbose_name': 'Pase',
                'verbose_name_plural': 'Pases',
                'ordering': ['match', 'minute'],
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(verbose_name='Minuto')),
                ('x_coordinate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Coord X')),
                ('y_coordinate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Coord Y')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Distancia (m)')),
                ('angle', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ángulo (°)')),
                ('body_part', models.CharField(choices=[('right', 'Pie Derecho'), ('left', 'Pie Izquierdo'), ('head', 'Cabeza'), ('other', 'Otro')], default='right', max_length=20, verbose_name='Parte del Cuerpo')),
                ('situation', models.CharField(choices=[('open_play', 'Jugada Abierta'), ('free_kick', 'Tiro Libre'), ('penalty', 'Penal'), ('corner', 'Córner'), ('cross', 'Centrada')], default='open_play', max_length=30, verbose_name='Situación')),
                ('is_goal', models.BooleanField(default=False, verbose_name='Es Gol')),
                ('xg_value', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='xG')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='matches.match', verbose_name='Partido')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='players.player', verbose_name='Jugador')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='teams.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Tiro',
                'verbose_name_plural': 'Tiros',
                'ordering': ['match', 'minute'],
            },
        ),
    ]
