# Generated by Django 6.0.4 on 2026-04-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('position', models.CharField(choices=[('goalkeeper', 'Portero'), ('defender', 'Defensa'), ('midfielder', 'Centrocampista'), ('forward', 'Delantero')], max_length=20, verbose_name='Posición')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nacionalidad')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Altura (m)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Peso (kg)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['team', 'number', 'name'],
                'unique_together': {('team', 'number')},
            },
        ),
    ]
