# Generated by Django 6.0.4 on 2026-04-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('stadium', models.CharField(max_length=200, verbose_name='Estadio')),
                ('coach', models.CharField(max_length=200, verbose_name='Entrenador')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name='Logo')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Fundación')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='leagues.league', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['name'],
                'unique_together': {('name', 'league')},
            },
        ),
    ]
