# Generated by Django 6.0.4 on 2026-04-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_possession', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='Posesión Local %')),
                ('away_possession', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='Posesión Visitante %')),
                ('home_shots', models.PositiveIntegerField(default=0, verbose_name='Tiros Local')),
                ('away_shots', models.PositiveIntegerField(default=0, verbose_name='Tiros Visitante')),
                ('home_shots_on_target', models.PositiveIntegerField(default=0, verbose_name='Tiros a Puerta Local')),
                ('away_shots_on_target', models.PositiveIntegerField(default=0, verbose_name='Tiros a Puerta Visitante')),
                ('home_passes', models.PositiveIntegerField(default=0, verbose_name='Pases Local')),
                ('away_passes', models.PositiveIntegerField(default=0, verbose_name='Pases Visitante')),
                ('home_pass_accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Precisión de Pases Local %')),
                ('away_pass_accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Precisión de Pases Visitante %')),
                ('home_fouls', models.PositiveIntegerField(default=0, verbose_name='Faltas Local')),
                ('away_fouls', models.PositiveIntegerField(default=0, verbose_name='Faltas Visitante')),
                ('home_corners', models.PositiveIntegerField(default=0, verbose_name='Córners Local')),
                ('away_corners', models.PositiveIntegerField(default=0, verbose_name='Córners Visitante')),
                ('home_yellow_cards', models.PositiveIntegerField(default=0, verbose_name='Tarjetas Amarillas Local')),
                ('away_yellow_cards', models.PositiveIntegerField(default=0, verbose_name='Tarjetas Amarillas Visitante')),
                ('home_red_cards', models.PositiveIntegerField(default=0, verbose_name='Tarjetas Rojas Local')),
                ('away_red_cards', models.PositiveIntegerField(default=0, verbose_name='Tarjetas Rojas Visitante')),
                ('home_offsides', models.PositiveIntegerField(default=0, verbose_name='Fuera de Lugar Local')),
                ('away_offsides', models.PositiveIntegerField(default=0, verbose_name='Fuera de Lugar Visitante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='matches.match', verbose_name='Partido')),
            ],
            options={
                'verbose_name': 'Dato Analítico',
                'verbose_name_plural': 'Datos Analíticos',
            },
        ),
    ]
