# Generated by Django 6.0.4 on 2026-04-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('stadium', models.CharField(blank=True, max_length=200, verbose_name='Estadio')),
                ('home_score', models.PositiveIntegerField(default=0, verbose_name='Goles Local')),
                ('away_score', models.PositiveIntegerField(default=0, verbose_name='Goles Visitante')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En Progreso'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('round_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jornada')),
                ('attendance', models.PositiveIntegerField(blank=True, null=True, verbose_name='Espectadores')),
                ('referee', models.CharField(blank=True, max_length=200, verbose_name='Árbitro')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team', verbose_name='Equipo Visitante')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team', verbose_name='Equipo Local')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.league', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-date'],
                'unique_together': {('home_team', 'away_team', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(verbose_name='Minuto')),
                ('event_type', models.CharField(choices=[('goal', 'Gol'), ('assist', 'Asistencia'), ('pass', 'Pase'), ('shot', 'Tiro'), ('foul', 'Falta'), ('yellow_card', 'Tarjeta Amarilla'), ('red_card', 'Tarjeta Roja'), ('tackle', 'Entrada')], max_length=20, verbose_name='Tipo de Evento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_own_goal', models.BooleanField(default=False, verbose_name='Gol en Contra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match', verbose_name='Partido')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='players.player', verbose_name='Jugador')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='teams.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Evento del Partido',
                'verbose_name_plural': 'Eventos del Partido',
                'ordering': ['match', 'minute'],
            },
        ),
    ]
